spring:
    datasource:
      url: "jdbc:mysql://localhost/nbttdbs"
      username: nbttdata
      password: nbttlong
    sql:
      init:
        mode: always
        encoding: UTF-8

mybatis:
  configuration:
    map-underscore-to-camel-case: true